### ISSUE TITLE
Python 2.5 Incompatible

### ISSUE THREAD

**Issue by pizzapanther** [klen/python-scss#16]
Tried to use with Python 2.5 on Google App Engine and got the following errors.  Submitting a patch soon.

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scss/parser.py", line 9, in <module>
    from scss.base import Node, Empty, ParseNode, ContentNode, IncludeNode
  File "scss/base.py", line 4, in <module>
    class Node(object):
  File "scss/base.py", line 40, in Node
    @ctx.setter
AttributeError: 'property' object has no attribute 'setter'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scss/parser.py", line 10, in <module>
    from scss.control import Variable, Expression, Function, Mixin, Include, MixinParam, Extend, Variables, Option, FunctionDefinition, FunctionReturn, If, For, SepValString
  File "scss/control.py", line 87
    return func(*params, root=self.root, name=name)
                            ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scss/parser.py", line 10, in <module>
    from scss.control import Variable, Expression, Function, Mixin, Include, MixinParam, Extend, Variables, Option, FunctionDefinition, FunctionReturn, If, For, SepValString
  File "scss/control.py", line 3, in <module>
    from scss.function import FUNCTION_LIST, unknown, warn
  File "scss/function.py", line 7, in <module>
    from itertools import product
ImportError: cannot import name product
```

**Comment by klen** [comment]
Thanks! Version 0.8.70 on pypi.
